language: java
branches:
  only:
  - release
  - netty_only
jdk:
- oraclejdk10
cache:
  directories:
  - "$HOME/.m2/repository"
deploy:
  provider: bintray
  file: target/descriptor.json
  user: fbacchella
  skip_cleanup: true
  on: release
  key:
    secure: hliXllPBU8/qj9QnmyMgknds5FiKhPcnGVtWV8oTDu7sMHua3W4/AI9og8SYREliR1W8VpIrPuB3PpmbLZjttT0KzNtDaJfyeswZatQ++W2fCAIibW9ID+6hheX0okM/IRa+kPGBxsTdAnm6FGWA5AqbFHuW2kx13Ms3HNurPTtLd1/xChaHGjgVt7zHWhroiMlINWsh3wnMW6+Xa6B3nxgMR6eu4B2+4u/9fpCWNi5F2em2FaMNhVOyFOgGIhvySsK9y/2f7u5HKdNJXptCHqS9Y9WMwVupje+wLbJqDVxnI3MLiaSh1l4MgU1gGcGC7GpzbyqjUyXIeluYiZO7ZdgOcjlsvfZ6OJbT17VuTPQkQnBeaI3kG0p+ZHlO6i2/Fu/s5KnCop1scX9pwNbJyXKtVzix2QwZ7mzweP6jYNI92eOP4z5oS1U7h9e9VVWG/FnbAbOYSuA7JuS8HsYeE4eoGgTqUa1x8Uufgd2QwYykM39cCjMImZkg+SLpXETDxkaCrrzNMHwCJHmLggBoX4dZcJqp3MRMJ63DTxohDrRZK+0M/PocK1isDORhX7UMzgqCfoX3mjB+VzN3RXyrvNHfWfQH6KVyOpU0+PSxiJIOsJsYqvE/j7bEpnSFbuRwiSz0wp+twy+BD/SkWpWGJvgRtOmbs/nHPMrvMbGf47Y=
