sudo: false
install: true
branches:
  only:
  - master
  - netty_only
addons:
  sonarcloud:
    organization: "fbacchella-github"
    token:
      secure: "XWJ0wVivuMHEgvTPvKaXhC5u7+SZfT/XYDC/YkksoFKQmGn7TO2HuwJq9DK7WOXrI5lJC/VKppcLJqwVVh4t7Sk+lz4VJm1vh1dzYwYRIDPguyTRArmw5XHe58QxFvKGTvtO/1BR7/hYYug+n6I3vU8h8M/El+f7inKwzJZYBqg="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
